# Generated by Django 5.1.7 on 2025-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestassignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
