# Generated by Django 5.1.7 on 2025-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestresult',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
