const trashData = [
	{
		category: "일반 쓰레기",
		items: [
			{
				id: 1,
				name: "휴지",
				howToDispose: `- 화장실에서 주로 사용하는 두루마리 휴지는 화장실 변기에 버려요. 변기에 버리지 않을 경우엔 일반쓰레기(종량제봉투)로 버려주세요. 
							   - 휴지를 모두 사용하고 남은 종이 휴지심은 종이로 분리배출해요. 티슈(미용화장지)나 물티슈는 반드시 일반쓰레기(종량제봉투)로 버려주세요. 
							     두루마리 휴지처럼 변기에 버리면 절대 안됩니다!`,
				recyclable: false,
				categories: ["일반 쓰레기"],
			},
			{
				id: 2,
				name: "종이컵",
				howToDispose: `- 일회용 종이컵은 음료나 이물질이 묻어있지 않은 상태로 배출해야만 재활용이 가능해요. 음료를 마신 후 종이컵 안쪽을 물로 깨끗이 헹궈낸 뒤 종이팩 종이컵 분리 수거으로 분리배출해주세요.
							   - 카페에서 테이크아웃한 일회용 종이컵의 플라스틱 뚜껑 등은 분리해서 재질별로 분리배출해요.
							   - 일회용 종이컵은 낱개로 배출하는 것보다 여러개를 한번에 모아서 배출할 경우 재활용될 가능성이 높습니다. 사용한 종이컵을 한곳에 모아두었다가 투명비닐 등에 넣어서 분리배출하는 것을 추천드립니다.
							   - 음료나 이물질에 오염되어 세척이 불가능한 종이컵은 일반쓰레기(종량제봉투)로 버려주세요.`,
				recyclable: true,
				categories: ["일반 쓰레기"],
			},
			{
				id: 3,
				name: "생선 뼈",
				howToDispose: `- 크기 작은 것은 음식물로, 큰 뼈는 일반 쓰레기로 구분합니다.`,
				recyclable: false,
				categories: ["일반 쓰레기", "음식물 쓰레기"],
			},
			{
				id: 4,
				name: "라이터",
				howToDispose: `- 라이터 내부에 소량의 가스만 남아있다면 폭발의 위험은 거의 없으니 그냥 버리면 되고, 가스가 많이 남아있다면 최대한 소진한 후 버리시기 바랍니다.`,
				recyclable: false,
				categories: ["일반 쓰레기"],
			},
			{
				id: 5,
				name: "핫팩",
				howToDispose: `- 핫팩 내부의 철가루와 포장재(부직포)는 모두 재활용이 불가능합니다. 통째로 일반쓰레기(종량제봉투)로 버려주세요.`,
				recyclable: false,
				categories: ["일반 쓰레기"],
			},
			{
				id: 6,
				name: "공",
				howToDispose: `- 구기운동에서 사용하는 공은 가죽, 합성고무 등을 여러겹 겹쳐서 만드는데 모두 재활용이 불가능한 재질입니다. 바람을 빼고 부피를 최대한 줄여서 일반쓰레기(종량제봉투)로 버려주세요.`,
				recyclable: false,
				categories: ["일반 쓰레기"],
			},
			{
				id: 7,
				name: "커터칼",
				howToDispose: `- 날카로운 칼날이 종량제 봉투를 찢고 나와 수거하는 분이 다치는 경우가 있으니 커터칼을 신문지 등으로 밀봉해서 버려주세요. 칼날만 따로 버려야 한다면 여러겹의 종이로 싸고 테이프로 단단히 고정해서 종량제봉투에 넣어주세요.`,
				recyclable: false,
				categories: ["일반 쓰레기"],
			},
			{
				id: 8,
				name: "볼펜",
				howToDispose: `- 볼펜 등의 플라스틱 필기구는 부피가 작고, 고무 손잡이, 쇠 스프링 등 다른 재질이 혼합되어 있어서 재활용이 불가능해요. 모두 일반쓰레기 (종량제봉투)로 버려주세요.`,
				recyclable: false,
				categories: ["일반 쓰레기"],
			},
			{
				id: 9,
				name: "우산",
				howToDispose: `- 우산은 플라스틱, 알루미늄, 합성섬유 등 여러 재질이 섞여있어 재활용이 불가능하니 통째로 일반쓰레기(종량제봉투)로 버려주세요. `,
				recyclable: false,
				categories: ["일반 쓰레기"],
			},
			{
				id: 10,
				name: "동물 뼈",
				howToDispose: `- 닭고기, 소고기, 돼지고기, 생선 등을 먹고 남은 뼈는 일반쓰레기 (종량제봉투)로 버려요.`,
				recyclable: false,
				categories: ["일반 쓰레기"],
			},
		],
	},
	{
		category: "재활용 쓰레기",
		items: [
			{
				id: 11,
				name: "페트병",
				howToDispose: `- 내용물을 비우고 라벨 제거 후 찌그러뜨려 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 12,
				name: "캔",
				howToDispose: `- 내용물 비우고 물로 헹군 후 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 13,
				name: "종이박스",
				howToDispose: `- 테이프 제거 후 평평하게 접어 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 14,
				name: "우유팩",
				howToDispose: `- 내용물 비우고 물로 헹군 후 종이팩 전용 수거함에 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 15,
				name: "페트병 뚜껑",
				howToDispose: `- 페트병과 페트병 뚜껑은 다른 재질이므로 분리해서 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 16,
				name: "스티로폼",
				howToDispose: `- 깨끗한 상태로 이물질 제거 후 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 17,
				name: "신문지",
				howToDispose: `- 이물질 제거 후 묶어서 종이류로 배출합니다.
							   - 신문지는 함께 끈으로 묶어서 배출하면 좋습니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 18,
				name: "잡지",
				howToDispose: `- 코팅되지 않은 경우 종이류로 묶어서 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 19,
				name: "종이컵",
				howToDispose: `- 내용물 비우고 물로 헹군 후 종이류로 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 20,
				name: "플라스틱 용기",
				howToDispose: `- 내용물 비우고 깨끗이 세척 후 배출합니다.
							   - 번거롭더라도 잘 지워지지 않는 기름기는 세제를 사용하여 세척합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 21,
				name: "비닐 포장지",
				howToDispose: `- 이물질 없는 경우 비닐류로 배출합니다.
							   - 스티커나 테이프, 접착제가 붙어있으면 완전히 떼어내서 일반쓰레기로 버리고 비닐만 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 22,
				name: "음료수 병",
				howToDispose: `- 내용물 비우고 물로 헹군 후 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 23,
				name: "유리병",
				howToDispose: `- 뚜껑 제거 후 내용물 비우고 배출합니다.
							   - 겉면의 상표 등의 라벨은 제거할 수 있으면 떼어낸 후 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 24,
				name: "알루미늄 호일",
				howToDispose: `- 음식물 제거 후 가능한 경우 캔류로 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 25,
				name: "계란판 (종이)",
				howToDispose: `- 회색 또는 흰색을 띄는 종이 계란판은 종이로 분리배출합니다.
							   - 보통 분홍빛을 띄는 투명 플라스틱 계란판은 플라스틱으로 분리배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 26,
				name: "종이 쇼핑백",
				howToDispose: `- 비닐 코팅 부분 제거 후 종이류로 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 27,
				name: "택배 상자",
				howToDispose: `- 테이프와 스티커 제거 후 평평하게 접어 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 28,
				name: "플라스틱 빨대",
				howToDispose: `- 깨끗이 씻어서 플라스틱류로 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 29,
				name: "음식 포장 플라스틱",
				howToDispose: `- 음식물 제거 후 세척해서 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 30,
				name: "아이스팩",
				howToDispose: `- 내용물 비우고 비닐로 분리배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 31,
				name: "계량 스푼 (플라스틱)",
				howToDispose: `- 세척 후 플라스틱류로 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 32,
				name: "빵 봉투 클립",
				howToDispose: `- 플라스틱으로 분류해 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 33,
				name: "화장품",
				howToDispose: `- 화장품은 제품에 따라 플라스틱, 유리병, 알루미늄 튜브 등 다양한 재질이 쓰이기 때문에 제품에 표기된 분리 배출 표시를 잘 확인한 후 버립니다.
							   - 또한 화장품통 내부에 남아있는 내용물을 최대한 비워낸 후 버려야 하고, 대부분의 화장품은 화학제품이므로 쉽게 물로 흘려보내선 안됩니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 34,
				name: "요구르트 병",
				howToDispose: `- 세척 후 플라스틱류로 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
			{
				id: 35,
				name: "참치캔",
				howToDispose: `- 내용물 제거 후 캔류로 배출합니다.`,
				recyclable: true,
				categories: ["재활용 쓰레기"],
			},
		],
	},
	{
		category: "음식물 쓰레기",
		items: [
			{
				id: 36,
				name: "사과껍질",
				howToDispose: `- 물기 제거 후 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 37,
				name: "계란 껍데기",
				howToDispose: `- 일반 쓰레기로 배출합니다. (음식물 아님)`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 38,
				name: "바나나 껍질",
				howToDispose: `- 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 39,
				name: "채소 껍질",
				howToDispose: `- 물기 제거 후 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 40,
				name: "감자 껍질",
				howToDispose: `- 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 41,
				name: "쌀뜨물",
				howToDispose: `- 하수구에 버리지 말고 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 42,
				name: "생선 내장",
				howToDispose: `- 물기 제거 후 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 43,
				name: "닭뼈",
				howToDispose: `- 일반 쓰레기로 배출합니다. (음식물 아님)`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 44,
				name: "멸치머리",
				howToDispose: `- 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 45,
				name: "김치",
				howToDispose: `- 양념 제거 후 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 46,
				name: "떡",
				howToDispose: `- 소량은 음식물 쓰레기로, 다량은 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 47,
				name: "오렌지 껍질",
				howToDispose: `- 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 48,
				name: "복숭아 씨",
				howToDispose: `- 일반 쓰레기로 배출합니다. (단단한 씨는 음식물 아님)`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 49,
				name: "조개껍데기",
				howToDispose: `- 일반 쓰레기로 배출합니다. (음식물 아님)`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 50,
				name: "커피 찌꺼기",
				howToDispose: `- 커피를 내린 후 남은 커피 가루나 오래돼서 먹을 수 없는 원두는 모두 일반쓰레기(종량제봉투)로 버립니다.
							   - 음식물 쓰레기는 살균 처리와 고온 건조 과정을 거쳐 경작용 퇴비 또는 동물용 사료로 재활용됩니다. 그러나 커피 찌꺼기는 질소 함유량이 높아 땅을 산성화시킬 수 있고, 카페인 성분 때문에 동물에게도 부적합합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 51,
				name: "사골 뼈",
				howToDispose: `- 일반 쓰레기로 배출합니다. (뼈류는 음식물 아님)`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 52,
				name: "김",
				howToDispose: `- 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 53,
				name: "라면 국물",
				howToDispose: `- 하수구에 버립니다. 음식물 쓰레기 아님.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 54,
				name: "우유",
				howToDispose: `- 소량은 하수구에, 대량은 지자체 지침에 따라 처리합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 55,
				name: "콩나물 뿌리",
				howToDispose: `- 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 56,
				name: "양파 껍질",
				howToDispose: `- 일반 쓰레기로 배출합니다. (섬유질이 많아 음식물 아님)`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 57,
				name: "옥수수 껍질",
				howToDispose: `- 일반 쓰레기로 배출합니다. (질긴 껍질은 음식물 아님)`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 58,
				name: "채소 줄기",
				howToDispose: `- 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
			{
				id: 59,
				name: "버섯 기둥",
				howToDispose: `- 음식물 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["음식물 쓰레기"],
			},
		],
	},
	{
		category: "가연성 쓰레기",
		items: [
			{
				id: 60,
				name: "비닐봉지",
				howToDispose: `- 이물질 없고 깨끗하면 재활용, 그렇지 않으면 일반 쓰레기입니다.`,
				recyclable: true,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 61,
				name: "플라스틱 랩",
				howToDispose: `- 이물질 없으면 재활용 가능하지만, 오염 시 일반 쓰레기로 배출합니다.`,
				recyclable: true,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 62,
				name: "휴지",
				howToDispose: `- 사용한 휴지는 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 63,
				name: "기저귀",
				howToDispose: `- 내용물 비우고 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 64,
				name: "종이 타월",
				howToDispose: `- 오염된 경우 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 65,
				name: "종이컵",
				howToDispose: `- 내용물 제거하고 깨끗하면 재활용, 오염 시 일반 쓰레기입니다.`,
				recyclable: true,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 66,
				name: "영수증",
				howToDispose: `- 감열지로 재활용 불가하므로 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 67,
				name: "사진 인화지",
				howToDispose: `- 재활용 불가로 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 68,
				name: "라면 봉지",
				howToDispose: `- 깨끗이 씻으면 재활용, 그렇지 않으면 일반 쓰레기입니다.`,
				recyclable: true,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 69,
				name: "과자 봉지",
				howToDispose: `- 내부 은박 처리된 경우 재활용 불가, 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 70,
				name: "티백",
				howToDispose: `- 일반 쓰레기로 배출합니다.
							   - 멸치, 다시마 등의 육수용 티백은 내용물을 티백에서 꺼내 음식물쓰레기로 배출하는 것도 가능합니다. 티백 껍데기는 일반쓰레기로 버립니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 71,
				name: "빨대",
				howToDispose: `- 재질이 다르면 재활용 어려워 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 72,
				name: "테이프",
				howToDispose: `- 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 73,
				name: "풍선",
				howToDispose: `- 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 74,
				name: "담배꽁초",
				howToDispose: `- 불을 완전히 끈 후 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 75,
				name: "분무기 용기",
				howToDispose: `- 내용물을 비운 뒤 재활용이 어려우면 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 76,
				name: "종이 포장재",
				howToDispose: `- 깨끗하면 재활용, 오염되면 일반 쓰레기로 배출합니다.`,
				recyclable: true,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 77,
				name: "종이 라벨",
				howToDispose: `- 접착제 등으로 오염되었을 경우 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 78,
				name: "빨간색 종이",
				howToDispose: `- 염료 처리된 경우 재활용 불가, 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 79,
				name: "포장용 완충제",
				howToDispose: `- 플라스틱 재질 확인 후, 재활용 불가능하면 일반 쓰레기입니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
			{
				id: 80,
				name: "이쑤시개",
				howToDispose: `- 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["가연성 쓰레기"],
			},
		],
	},
	{
		category: "불연성 쓰레기",
		items: [
			{
				id: 81,
				name: "도자기 조각",
				howToDispose: `- 도자기는 재활용이 불가능하고 불에 타지 않는 쓰레기이므로 불연성 쓰레기 봉투(마대)에 넣어서 버려주세요.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 82,
				name: "거울",
				howToDispose: `- 종이에 감싸 일반 쓰레기로 배출하거나 주민센터에 문의합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 83,
				name: "깨진 유리",
				howToDispose: `- 신문지나 두꺼운 종이에 싸서 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 84,
				name: "세라믹 접시",
				howToDispose: `- 깨졌다면 조각을 감싸 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 85,
				name: "형광등",
				howToDispose: `- 깨지지 않게 포장해 가까운 폐형광등 수거함에 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 86,
				name: "도자기 화분",
				howToDispose: `- 흙 제거 후 깨진 경우 감싸서 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 87,
				name: "도자기 인형",
				howToDispose: `- 포장 후 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 88,
				name: "접착 테이프 묻은 유리",
				howToDispose: `- 접착물이 있으면 재활용 불가, 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 89,
				name: "유리컵",
				howToDispose: `- 재질이 일반 유리라면 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 90,
				name: "유리 접시",
				howToDispose: `- 신문지 등에 감싸 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 91,
				name: "도자기 타일",
				howToDispose: `- 소량은 일반 쓰레기, 대량은 폐기물로 분류되어 처리업체에 문의합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 92,
				name: "내열유리 용기",
				howToDispose: `- 깨지면 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 93,
				name: "소금",
				howToDispose: `-식당 등에서 대량으로 버려야할 경우 불연성 쓰레기 봉투로 버리거나 주민센터/구청 등에 생활폐기물로 신고/배출해주세요.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 94,
				name: "자동차 전구",
				howToDispose: `- 파손 주의하여 일반 쓰레기로 배출하거나 수거소에 문의합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 95,
				name: "깨진 화장품 용기 (유리)",
				howToDispose: `- 신문지에 싸서 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 96,
				name: "전기히터 유리커버",
				howToDispose: `- 파손 시 조심히 포장 후 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 97,
				name: "강화유리 파편",
				howToDispose: `- 작은 조각은 종이에 감싸 일반 쓰레기로, 큰 유리는 관할 지자체 문의합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 98,
				name: "유리 액자",
				howToDispose: `- 유리는 신문지로 감싸 일반 쓰레기로, 나무나 금속은 분리 후 처리합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 99,
				name: "백열전구",
				howToDispose: `- 깨지지 않게 포장 후 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 100,
				name: "깨진 어항",
				howToDispose: `- 유리조각 주의하여 포장 후 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 101,
				name: "가정용 세면대 파편",
				howToDispose: `- 일반 쓰레기로는 어려우며, 대형 폐기물로 분류되어 처리업체에 문의합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
			{
				id: 102,
				name: "도자기 찻잔",
				howToDispose: `- 깨졌다면 감싸서 일반 쓰레기로 배출합니다.`,
				recyclable: false,
				categories: ["불연성 쓰레기"],
			},
		],
	},
];

export default trashData;
